[project]
name = "soloq-ranking"

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn -k eventlet -w 1 app:app"
restartPolicyType = "ON_FAILURE"

[env]
FLASK_ENV = "production"
FLASK_APP = "app.py"

[services]
  [[services.web]]
  name = "soloq-ranking-web"
  port = 8080
  healthcheckPath = "/"
  healthcheckTimeout = 60